<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TRENZ.Lib.RazorMail.MicrosoftGraph</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Identity"/>
        <PackageReference Include="Microsoft.Graph"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TRENZ.Lib.RazorMail.Core\TRENZ.Lib.RazorMail.Core.csproj"/>
    </ItemGroup>

</Project>
